# Generated by Django 2.2 on 2021-10-23 20:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('session_id', models.UUIDField()),
                ('category', models.CharField(max_length=45)),
                ('name', models.CharField(max_length=45)),
                ('host', models.CharField(choices=[('www.consumeraffairs.com', 'www.consumeraffairs.com'), ('www.consumeraffairs2.com', 'www.consumeraffairs2.com'), ('www.consumeraffairs3.com', 'www.consumeraffairs3.com')], max_length=35)),
                ('path', models.CharField(max_length=100)),
                ('element', models.CharField(blank=True, max_length=50)),
                ('first_name', models.CharField(blank=True, max_length=100)),
                ('last_name', models.CharField(blank=True, max_length=100)),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
