# Generated by Django 2.2 on 2021-10-23 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eye', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='element',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='first_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='events',
            name='last_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
